### PR TITLE
Specify the version of the GPL explicitly

### LINKED ISSUE #8: What version of the GPL?
The permission statement in library header does not specify what version of the GPL this is released under. The statement should read something like:

```lisp
;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published
;; by the Free Software Foundation, either version 3 of the License,
;; or (at your option) any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this file.  If not, see <http://www.gnu.org/licenses/>.
```

Thanks!

### PR DESCRIPTION
**Pull request by tarsius**
Change the license from "the" GPL to GPL "either version 3, or (at your option) any later version.

Xavier Décoret (@Xadeck) has given us permission to do so at #8.
Closes #8.

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

**Comment by tarsius** [comment]
Uh wait, I *closed* this (not *merged*). Is that what you intended to do?

**Comment by jimhourihan** [comment]
No, sorry I’m trying to fix it now.

   -Jim

**Comment by jimhourihan** [comment]
Ok, it should be all good now.

  -Jim

**Pull request merged**
